### PR TITLE
Kubernetes Master Stuck

### PR DESCRIPTION
**Pull request by VariableDeclared**
Added logic to check for global client certificates
in a case where they are not available.

If per-client certificates are not found i.e. {}
then fallback to getting global client certs.

[LP#1825819](https://bugs.launchpad.net/charm-kubernetes-master/+bug/1825819)

[Related PR](https://github.com/charmed-kubernetes/charm-kubernetes-master/pull/42)
---

### CODE REVIEW

**Review by kwmonroe — COMMENTED** [review]
@VariableDeclared this LGTM, but I'd like @johnsca to weigh in.

This currently works around the fact that `tls.client_certs_map` only includes data from [units.received](https://github.com/charmed-kubernetes/interface-tls-certificates/blob/master/requires.py#L236), yet some clients may have done a `to_publish_raw`.  We have to get that data from the deprecated `get_client_cert` because that's what does a [units.received_raw](https://github.com/charmed-kubernetes/interface-tls-certificates/blob/master/requires.py#L171).

@johnsca if the above is accurate, we could either go with the workaround in this PR, or adjust [client_certs](https://github.com/charmed-kubernetes/interface-tls-certificates/blob/master/requires.py#L231) so that it merges both `units.received` and `units.received_raw`.  What do you think?

**Comment by VariableDeclared** [comment]
~~Regarding our conversation the cert save change is listened for [here](https://github.com/charmed-kubernetes/charm-kubernetes-master/blob/688a1910aa257d47dde62f536de1750e2f0691bb/reactive/kubernetes_master.py#L740)  which is triggered [here](https://github.com/juju-solutions/layer-tls-client/blob/7bfc407b4f7e1811c682412ba4cca8f360356215/reactive/tls_client.py#L149). I'll await the review to see if this is sufficient.~~

**Comment by VariableDeclared** [comment]
Created draft PR for [Kubernetes master](https://github.com/charmed-kubernetes/charm-kubernetes-master/pull/42)

**Review by johnsca — APPROVED** [review]
Discussed on IRC last week but I forgot to copy my comments here.  I'm not terribly happy with the need for this workaround, but I don't see any other way to handle it.  Does require the linked change on the k8s side as well to handle the fact that the CN on the client cert won't match.

**Comment by Cynerva** [comment]
I'm merging this because it has approving reviews, and @VariableDeclared confirmed on IRC that it's been tested. Cheers.

**Pull request merged**
